window.__ADVFR__={
root:["🌱","Matcha Flavoured","Bienvenue ! Cet arbre suit les vrais succès du pack, qui servent de tutoriel. Touche une étape débloquée pour un indice.",[],""],
light_campfire:["🔥","Allumer un kindling","Le feu de camp s'appelle « petit bois » (kindling) et se fabrique éteint. Il te faut de quoi l'allumer avec ce qui pousse au sol.",["Kindling","Tinder","Fire Starter"],"Crafte le kindling, puis allume-le avec du amadou (usage unique) ou un allume-feu."],
obtain_dry_grass:["🌾","Herbe sèche","L'herbe ne se ramasse plus à mains nues, et une fois récoltée elle doit passer sur le feu.",["Short Dry Grass","Tall Dry Grass"],"Coupe l'herbe à la houe ou aux cisailles (à la houe, parfois des graines de blé). Fais-la cuire sur le petit bois ou au four."],
obtain_kiln:["🏺","Mud kiln","Mélange ton herbe sèche avec quelque chose de très commun sous tes pieds.",["Packed Mud","Mud Bricks","Mud Kiln"],"Le four en terre cuite remplace le fumoir : il cuit le cuivre, la pierre, le verre et les briques, mais ne fait que carboniser la nourriture."],
obtain_copper:["🟠","Cuivre","Ton premier métal se fond dans ce que tu viens de construire.",["Copper Ingot"],"Les outils en cuivre minent deepslate, fer et argent, pas l'or ni le diamant. Il n'y a pas d'outils en pierre."],
craft_brush:["🖌️","Pinceau","Le cuivre permet de fouiller le passé.",["Brush"],"Le pinceau se fabrique comme en vanilla (plume, lingot de cuivre, bâton). Sers-t'en sur le sable et le gravier suspects."],
obtain_fetish:["🗿","Clay fetish","Creuse délicatement dans les ruines…",[],"Les statuettes d'argile (cheerful et mournful) se trouvent en archéologie ou chez l'archéologue (niveau 5). Elles changent la météo : beau temps ou pluie."],
obtain_mattock:["⛏️","Outils hybrides","Et si un seul outil en remplaçait deux pour libérer ta barre d'action ?",[],"Mattock et dolabra combinent chacun deux outils, dès le cuivre."],
obtain_smooth_stone:["🪨","Pierre lisse","Le kiln sait cuire la roche, deux fois de suite.",["Limestone","Smooth Stone"],"Cobblestone → limestone (la « pierre ») → smooth stone, au four en terre cuite."],
obtain_blast_furnace:["🏭","Haut-fourneau","Il faut plus chaud. Pense à la pierre lisse… et à la roche des profondeurs.",["Blast Furnace"],"Fer, or, argent et diamant ne se fondent qu'au haut-fourneau. Il transforme aussi cobblestone → gravier → sable."],
obtain_iron_ingot:["⚙️","Fer","Le haut-fourneau ouvre enfin la porte au fer.",["Iron Ingot"],"Les outils en fer minent tout sauf l'obsidienne."],
obtain_carbon_rich_iron:["⚫","Fer carburé","Le fer seul ne suffit plus pour la forge. Ajoute du carbone.",["Carbon-Rich Iron"],""],
obtain_steel:["🔩","Acier","Repasse ton fer carburé dans le feu le plus chaud.",["Steel Alloy"],""],
obtain_smithing_table:["🔨","Table de forgeron","L'acier sert d'abord à construire ton atelier.",["Smithing Table"],"Les alliages s'appliquent ici sur l'équipement de base, sans template (sauf hybrides et claymores)."],
obtain_avil:["⚒️","Enclume","Elle aussi demande de l'acier.",["Anvil"],"Réparer n'a pas de plafond (jamais « Trop cher ! ») et coûte seulement 1 niveau par lingot. C'est aussi là que tu appliques les blessings."],
obtain_smithing_upgrade:["📜","Template d'amélioration","Les outils hybrides et les claymores en ont besoin pour passer en alliage.",["Netherite Upgrade Smithing Template"],""],
upgrade_mattock:["🛠️","Hybride en alliage","Ton mattock ou ta dolabra mérite mieux que du cuivre.",[],"Base + alliage + template d'amélioration à la table de forgeron."],
obtain_steel_tool:["🗡️","Outil en acier","L'acier s'applique sur le fer.",[],"Acier = gros recul et protection contre les explosions, très durable."],
obtain_gold:["🟡","Or","Le haut-fourneau fond aussi l'or.",["Gold Ingot"],"L'or est un palier secondaire, avec Fortune et Butin."],
obtain_shakudo:["🟣","Shakudo","Cuivre et or, en gros volumes.",["Shakudo Alloy"],""],
obtain_palatinate_tool:["🔮","Outil en shakudo","Le shakudo s'applique sur le cuivre.",[],"Outils avec Toucher de soie, épée qui vole de la vie, armure qui purifie des effets négatifs."],
obtain_adamant:["🛡️","Adamant","La netherite a changé de nom. Il te faut des débris, de l'or et quelque chose de divin.",["Adamant Alloy"],""],
obtain_adamant_tool:["💠","Outil en adamant","L'adamant s'applique sur le diamant.",[],"Les outils adamant cuisent automatiquement ce qu'ils minent."],
obtain_silver:["⚪","Argent","Un minerai qui remplace l'émeraude, presque partout. Les abbayes en cachent aussi.",["Silver Bullion"],"Le native silver donne du raw silver, à fondre au haut-fourneau en silver bullion."],
obtain_bronze:["🟤","Hepatizon","Beaucoup de cuivre, un peu d'argent et d'or.",["Hepatizon Alloy"],""],
obtain_bronze_tool:["🥉","Outil en hepatizon","L'hepatizon s'applique sur le cuivre.",[],"Très rapide à miner et te fait marcher plus vite."],
obtain_electrum:["🌟","Electrum","Or et argent ensemble, bénis par un fragment.",["Electrum Alloy"],""],
obtain_electrum_tool:["✨","Outil en electrum","L'electrum s'applique sur le diamant.",[],"Seule source de Fortune au-delà de I, et Butin. Les armes brûlent les morts-vivants."],
obtain_diamond:["💎","Diamant","Le minerai ne te donne plus un diamant tout prêt.",["Diamond"],"Le minerai lâche un raw diamond, à fondre au haut-fourneau."],
enter_nether:["😈","Entrer en Hell","Le Nether a changé de nom. Cuisine quelque chose qui protège du feu avant d'y aller.",[],"Mange du melon cuisiné avant le voyage (Résistance au feu)."],
find_stronghold:["👁️","Trouver la forteresse","Les yeux de l'Ender ne se font plus avec de la poudre de blaze.",["Ender Eye"],""],
cook_food:["🍳","Cuisiner","Plus de faim ni de régénération : manger soigne. Cuire un ingrédient réveille son effet caché.",["Baked Apple","Grilled Melon","Steamed Carrots"],"Onglet Cuisine pour tout le détail."],
obtain_oven:["♨️","Four (oven)","Le vrai four de cuisine demande du métal et des briques.",["Oven"],""],
obtain_bowl:["🥣","Bol","Pour servir les grands plats, il faut de la vaisselle… en terre cuite.",["Bowl"],""],
cook_pumpkin_curry:["🎃","Pumpkin curry","Le plus long des plats de four commence par un bouillon.",["Pumpkin Curry Stock"],"Crafte le stock, puis cuis-le au four (pas sur le petit bois)."],
obtain_green_curry:["🥬","Green curry","Un bouillon vert…",["Green Curry Stock"],"Crafte le stock puis fais-le cuire."],
obtain_japanese_curry:["🍛","Japanese curry","Un bouillon de curry classique.",["Curry Stock"],"Crafte le stock puis fais-le cuire."],
obtain_paneer_mahkani:["🧀","Paneer makhani","Fromage et tomates dans un bouillon.",["Paneer Curry Stock"],"Crafte le stock puis fais-le cuire."],
obtain_ramen:["🍜","Ramen","Un bouillon avec algues et œuf.",["Ramen Stock"],"Crafte le stock puis fais-le cuire."],
preserve_food:["🫙","Faire des conserves","Une fiole, un ingrédient et un agent de conservation.",["Pumpkin Jam","Pickled Carrots"],"Confitures : ingrédient cuit + sucre + fiole. Pickles : ingrédient + champignon brun + fiole."],
preserve_everything:["🏺","Toutes les conserves","Les a-t-on toutes faites ?",[],""],
cook_secret_food:["🤫","Ingrédient secret","Certains ingrédients rares (dorés, ou venus de Hell) ne sont pas dans le livre de recettes.",["Baked Golden Apple","Golden Steamed Carrots"],"Champignons crimson et warped, pomme dorée, carotte dorée : cuis-les comme leurs versions normales."],
cook_secret_meal:["🍱","Repas secret","Transforme ces ingrédients secrets en vrais plats.",[],"Mêmes recettes que les plats normaux, en remplaçant l'ingrédient par sa version secrète."],
obtain_estus:["🕯️","Estus","Les morts-vivants lâchent parfois quelque chose de lumineux.",[],"Ramasser du raw Estus te soigne un peu et le transforme en Estus Ash, l'épice et le matériau magique du pack."],
obtain_nazar:["🧿","Nazar","Un porte-bonheur bleu et blanc, rehaussé d'Estus.",["Nazar"],""],
smith_warding_sword:["⚔️","Épée de garde","Un nazar sur une épée la rend redoutable contre les morts.",[],""],
smith_silver_sword:["🗡️","Épée en argent","L'argent aussi brûle les morts-vivants.",[],""],
smith_warding_shield:["🛡️","Bouclier de garde","Protège-toi des morts avec un nazar.",[],""],
obtain_divine_fragment:["✴️","Fragment divin","Tu tombes sur un spawner. Tentant d'en faire une ferme… mais ce qu'il cache vaut plus.",["Divine Fragment"],"Casse les spawners (et bats des boss) pour obtenir des fragments divins. 9 fragments = 1 Divine Favour, et inversement."],
obtain_heart:["💖","Crystal heart","Chaque mort te coûte un cœur max. Il existe un moyen de les récupérer.",["Crystal Heart"],"Jusqu'à 30 cœurs. On en trouve aussi chez le bibliothécaire (niveau 5) et en butin."],
obtain_opal:["🤍","Opale","Une gemme gardée par un grand gardien des océans.",[],"Lâchée par l'Elder Guardian. Le joaillier l'utilise pour des bijoux."],
obtain_ruby:["❤️","Rubis","Cherche dans les bastions de Hell.",[],"Dans les coffres des bastions."],
obtain_amber:["🧡","Ambre","Les ruines anciennes cachent des trésors sous le sable.",[],"En archéologie dans les trail ruins (butin rare)."],
obtain_topaz:["💛","Topaze","Tout au fond, dans le silence…",[],"Dans les coffres des ancient cities."],
obtain_obol:["🪙","Obol","Les émeraudes ont changé de nom… et sont rares.",[],"Les succès en donnent. Seuls quelques villageois en paient : le pêcheur (poissons), le joaillier (gemmes) et le forgeron d'armes."],
light_beacon:["🏮","Appeler le marchand","Un feu spécial attire le marchand ambulant.",["Beacon Kindling"],"Pose et allume le petit bois-balise."],
trade_for_asylum_seeker:["🧳","Accueillir un villageois","Les villages sont vides. Le marchand ambulant connaît des gens qui cherchent un foyer.",[],"Achète un asylum seeker au marchand ambulant."],
kill_villager:["✝️","…","Tu ne devrais pas voir celui-là.",[],"Succès caché obtenu en tuant un villageois. À éviter."],
trade_fish:["🐟","Vendre du poisson","Un villageois achète ce que tu pêches.",[],"Le pêcheur achète les poissons contre des obols."],
catch_everything:["🎣","Pêcher tous les poissons","47 espèces selon l'eau et le climat.",[],"Voir l'onglet Pêche & mobs. Récompense : 10 obols."],
trade_everything:["🤝","Commercer avec tous","Fais au moins un échange avec chaque métier.",[],""]
};
